name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  client-id: 
    description: "client id of service principal used to authenticate with azure"
    required: true
  tenant-id: 
    description: "tenant id of service principal used to authenticate with azure"
    required: true
  subscription-id:
    description: "subscription id of service principal used to authenticate with azure"
    required: true
  script_parameter:
    description: "Parameters to execute code"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.MANAGED_IDENTITY_CLIENT_ID }}
        tenant-id: ${{ inputs.MANAGED_IDENTITY_TENANT_ID }}
        subscription-id: ${{ inputs.SUBSCRIPTION_ID }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
