name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  script_parameter:
    description: "Parameters to execute code"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
        tenant-id: ${{ secrets.MANAGED_IDENTITY_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
