---
name: PR Workflow for AI Search Components

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - 'development'

jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
