---
name: CI Workflow for AI Search Components

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'development'

env:
    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
    ACS_SERVICE_NAME: ${{ vars.ACS_SERVICE_NAME }}
    AOAI_BASE_ENDPOINT: ${{ vars.AOAI_BASE_ENDPOINT }}
    AI_FOUNDRY_PROJECT_URI: ${{ vars.AI_FOUNDRY_PROJECT_URI }}
    MANAGED_IDENTITY_CLIENT_ID: ${{ vars.MANAGED_IDENTITY_CLIENT_ID }}
    MANAGED_IDENTITY_NAME: ${{ vars.MANAGED_IDENTITY_NAME }}
    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}
    FEDERATED_CLIENT_ID: ${{ vars.FEDERATED_CLIENT_ID }}
    FUNCTION_APP_NAME: ${{ vars.FUNCTION_APP_NAME }}

permissions:
  id-token: write
  contents: read
jobs:
  deploy-and-evaluate:
    name: Deployment and Evaluation
    runs-on: ubuntu-latest
    container:
        image:  ${{ vars.ACR_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.IMAGE_NAME }}:latest
        options: --user root
        credentials:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0

      - name: Azure login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
            client-id: ${{ env.FEDERATED_CLIENT_ID }}
            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Execute Azure Functions Deployment
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.deploy_azure_functions --ignore_slot
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

      - name: Validate Azure Functions Deployment
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.run_functions --ignore_slot
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

      - name: Deploy Indexer
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.build_indexer --ignore_slot
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        
      - name: Execute search evaluation
        shell: bash
        run: |
            python -u -m mlops.evaluation.search_evaluation --gt_path "./mlops/evaluation/data/search_evaluation_data.jsonl" --semantic_config my-semantic-config
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

      - name: Get merged branch name
        id: get_branch_name
        run: |
          export LATESTLOG=$(git log -1 --pretty=%B)
          export SOURCEBRANCH=$(echo "$LATESTLOG" | head -n 1 | cut -d'/' -f2-)
          echo "The merged branch  name is $SOURCEBRANCH"
          echo "::set-output name=sourcebranch::$SOURCEBRANCH"

      - name: Cleanup PR Branch
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.cleanup_pr
        env:
            BUILD_SOURCEBRANCHNAME: ${{ steps.get_branch_name.outputs.sourcebranch }}
