---
name: PR Workflow for AI Search Components

on:
  pull_request:
    branches:
      - 'development'
  workflow_call:

jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
  deploy-azure-functions:
    name: Azure Functions Deployment
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Export Secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Configure Job Agent
        uses: ./.github/actions/configure_job_agent

      - name: Execute Azure Functions Deployment
        uses: ./.github/actions/execute_shell_code
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -u -m mlops.deployment_scripts.deploy_azure_functions

      - name: Validate Azure Functions Deployment
        uses: ./.github/actions/execute_shell_code
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -u -m mlops.deployment_scripts.run_functions

      - name: Deploy Indexer
        uses: ./.github/actions/execute_shell_code
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -u -m mlops.deployment_scripts.build_indexer
  run_search_evaluation:
    name: Run Search Evaluation
    runs-on: ubuntu-latest
    needs: deploy-azure-functions
    env:
      BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load Python Dependencies
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r .github/requirements/search_evaluation_requirements.txt
      - name: Execute search evaluation
        shell: bash
        run: |
          python -u -m mlops.evaluation.search_evaluation --gt_path "./mlops/evaluation/data/search_evaluation_data.jsonl" --semantic_config my-semantic-config
