---
name: PR Workflow for AI Search Components

on:
  pull_request:
    branches: [development]
  workflow_call:

env:
    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
    ACS_SERVICE_NAME: ${{ vars.ACS_SERVICE_NAME }}
    AOAI_BASE_ENDPOINT: ${{ vars.AOAI_BASE_ENDPOINT }}
    AI_STUDIO_PROJECT_NAME: ${{ vars.AI_STUDIO_PROJECT_NAME }}
    MANAGED_IDENTITY_CLIENT_ID: ${{ vars.MANAGED_IDENTITY_CLIENT_ID }}
    MANAGED_IDENTITY_NAME: ${{ vars.MANAGED_IDENTITY_NAME }}
    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  deploy-and-evaluate:
    name: Deployment and Evaluation
    runs-on: ubuntu-latest
    container:
        image: aipullacr.azurecr.io/devops_container_image:latest
        options: --user root
        credentials:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Azure login
        uses: azure/login@v2
        with:
            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Execute Azure Functions Deployment
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.deploy_azure_functions
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

      - name: Validate Azure Functions Deployment
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.run_functions
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}             

      - name: Deploy Indexer
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.build_indexer
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}              

      - name: Execute search evaluation
        shell: bash
        run: |
            python -u -m mlops.evaluation.search_evaluation --gt_path "./mlops/evaluation/data/search_evaluation_data.jsonl" --semantic_config my-semantic-config
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

      - name: Print results of search evaluation
        shell: bash
        run: |
            ls -t results/ | head -n 1 | xargs -I {} cat results/{}
