---
name: Build Validation Workflow

on:
  workflow_call:
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
        image:  ${{ vars.ACR_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.IMAGE_NAME }}:latest
        options: --user root
        credentials:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Code
        run: flake8

      - name: Run Unit Tests
        shell: bash
        run: |
          pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: "**/test-*.xml"
