---
name: Build Validation Workflow

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  get-acr-token:
    name: Get ACR Token
    runs-on: ubuntu-latest
    outputs:
      acr_token: ${{ steps.get_token.outputs.acr_token }}
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
            client-id: ${{ vars.FEDERATED_CLIENT_ID }}
            tenant-id: ${{ vars.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ vars.SUBSCRIPTION_ID }}
            
      - name: Get ACR Access Token
        id: get_token
        run: |
          TOKEN=$(az acr login --name ${{ vars.ACR_CONTAINER_REGISTRY }} --expose-token --output tsv --query accessToken)
          echo "::add-mask::$TOKEN"
          echo "acr_token=$TOKEN" >> $GITHUB_OUTPUT

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: get-acr-token
    container:
        image:  ${{ vars.ACR_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.IMAGE_NAME }}:latest
        options: --user root
        credentials:
            username: 00000000-0000-0000-0000-000000000000
            password: ${{ needs.get-acr-token.outputs.acr_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Code
        run: flake8

      - name: Run Unit Tests
        shell: bash
        run: |
          pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/test-*.xml"
