---
name: Data Initialization Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
    MANAGED_IDENTITY_CLIENT_ID: ${{ vars.MANAGED_IDENTITY_CLIENT_ID }}
    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}
    PYTHON_VERSION: "3.11"

permissions:
  id-token: write
  contents: read

jobs:
  upload-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load Python Dependencies
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt

      - name: Azure login
        uses: azure/login@v2
        with:
            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Upload toy data to the toy dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data

      - name: Upload full data to the full dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data --stage dev
            