---
name: Data Initialization Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
    FEDERATED_CLIENT_ID: ${{ vars.FEDERATED_CLIENT_ID }}
    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  upload-data:
    runs-on: ubuntu-latest
    container:
        image:  ${{ vars.ACR_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.IMAGE_NAME }}:latest
        options: --user root
        credentials:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0

      - name: Azure login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
            client-id: ${{ env.FEDERATED_CLIENT_ID }}
            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Upload toy data to the toy dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data

      - name: Upload full data to the full dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data --stage dev
            