---
name: Data Initialization Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
    MANAGED_IDENTITY_CLIENT_ID: ${{ vars.MANAGED_IDENTITY_CLIENT_ID }}
    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  upload-data:
    runs-on: ubuntu-latest
    container:
        image: aipullacr.azurecr.io/devops_container_image:latest
        options: --user root
        credentials:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Azure login
        uses: azure/login@v2
        with:
            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Upload toy data to the toy dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data

      - name: Upload full data to the full dataset
        shell: bash
        run: |
            python -u -m mlops.deployment_scripts.upload_data --stage dev
            