name: CI

on:
  push:
    branches:
      - 'newbase'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the merged branch name
        id: vars
        run: |
          echo "PR_BRANCH_NAME=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Use the branch name
        run: |
          echo "The merged branch name is $PR_BRANCH_NAME"